version: '3.8'
services:
  app:
    image: php:8.2-cli
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: tail -f /dev/null
  
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: solar_db
    ports:
      - "3306:3306"